# Generated by Django 2.2 on 2022-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
