# Generated by Django 2.2 on 2022-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerdetail',
            name='state',
            field=models.CharField(choices=[('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('Mymensingh', 'Mymensingh'), ('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Chitagong', 'Chitagong')], max_length=50, null=True),
        ),
    ]
