# Generated by Django 2.2 on 2022-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_auto_20220430_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='saler',
            field=models.CharField(default='mizanmart@admin', max_length=100),
        ),
    ]
